apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: webapps.example.com
spec:
  group: example.com
  scope: Namespaced
  names:
    plural: webapps 
    singular: webapp
    kind: WebApp
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                  maximum: 10
                  minimum: 1
                image:
                  type: string
                port:
                  type: integer
                  minimum: 1
                  maximum: 8080
              required:
                - replicas
                - image
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum: ["Pending", "Running", "Failed"]
                readyReplicas:
                  type: integer